import React, { useState } from 'react';
import { Link } from 'react-router-dom';
import {
  Leaf,
  ArrowRight,
  TrendingDown,
  Trophy,
  BrainCircuit,
  BarChart4,
  CheckCircle,
  HelpCircle,
  Mail,
  UserCheck
} from 'lucide-react';
import { motion } from 'framer-motion';

const LandingPage = () => {
  const [email, setEmail] = useState('');
  const [subscribed, setSubscribed] = useState(false);

  const stats = [
    { label: 'CO2e Diverted', value: '45,280 kg' },
    { label: 'Active Eco-Warriors', value: '1,240+' },
    { label: 'Trees Equivalent Saved', value: '1,890' },
    { label: 'Green Level Achieved', value: 'Guardian' }
  ];

  const features = [
    {
      title: 'Precision Log Engine',
      description: 'Easily track travel, electricity, meals, and waste. Configure factors dynamically to match exact regional emissions.',
      icon: Leaf,
      color: 'text-emerald-500 bg-emerald-500/10'
    },
    {
      title: 'Advanced Carbon Analytics',
      description: 'Interact with interactive trend lines, source ratios, and long-term emission projection models.',
      icon: BarChart4,
      color: 'text-cyan-500 bg-cyan-500/10'
    },
    {
      title: 'AI-Powered Recommendations',
      description: 'Receive personalized suggestions generated by looking at your trailing activity patterns. Instantly view estimated carbon savings.',
      icon: BrainCircuit,
      color: 'text-purple-500 bg-purple-500/10'
    },
    {
      title: 'Gamified Challenges & Streaks',
      description: 'Join community initiatives like No Plastic Week. Build habits, earn XP, scale leaderboards, and unlock eco-badges.',
      icon: Trophy,
      color: 'text-amber-500 bg-amber-500/10'
    }
  ];

  const faqs = [
    {
      q: 'How does Carbonlytix calculate my emissions?',
      a: 'We use verified carbon emission factor models published by agencies like the US EPA, UK DEFRA, and IPCC. For example, driving 10km in a petrol car uses a different factor than 10km in a hybrid or public bus.'
    },
    {
      q: 'Can I use this completely for free?',
      a: 'Yes, the core tracking features, calculation engine, challenges, and educational guides are entirely free to use. Premium subscriptions unlock advanced historical reporting and custom PDF exports.'
    },
    {
      q: 'How does the streak tracking work?',
      a: 'Maintaining a logging streak requires recording at least one carbon activity (e.g. food habit, energy reading, transport trip) every 24 hours. A streak rewards additional XP multipliers.'
    }
  ];

  const handleSubscribe = (e) => {
    e.preventDefault();
    if (email) {
      setSubscribed(true);
      setEmail('');
    }
  };

  return (
    <div className="min-h-screen bg-dark-50 text-dark-900 dark:bg-dark-950 dark:text-dark-100 overflow-x-hidden font-sans">
      {/* Navigation Header */}
      <header className="fixed top-0 left-0 right-0 z-40 border-b border-dark-200/50 dark:border-dark-900/50 bg-white/80 dark:bg-dark-950/80 backdrop-blur-md px-6 py-4 flex items-center justify-between">
        <div className="flex items-center gap-2 font-bold text-2xl tracking-tight">
          <Leaf className="w-8 h-8 text-brand-600 fill-brand-500/20" />
          <span>Carbon<span className="text-brand-500">lytix</span></span>
        </div>
        <div className="flex items-center gap-4">
          <Link to="/login" className="text-sm font-semibold hover:text-brand-600 dark:hover:text-brand-400 transition-colors">
            Sign In
          </Link>
          <Link to="/signup" className="btn-primary py-2 px-4 text-sm rounded-lg">
            Get Started
          </Link>
        </div>
      </header>

      {/* Hero Section */}
      <section className="pt-32 pb-20 px-6 max-w-7xl mx-auto flex flex-col lg:flex-row items-center gap-12 bg-grid-pattern">
        <div className="flex-1 flex flex-col gap-6 text-left">
          <div className="inline-flex items-center gap-2 px-3.5 py-1.5 rounded-full bg-brand-500/10 text-brand-600 dark:text-brand-400 font-semibold text-xs border border-brand-500/20 w-fit">
            <TrendingDown className="w-4 h-4" />
            <span>Empowering Sustainable Habit Changes</span>
          </div>
          <h1 className="text-5xl lg:text-6xl font-extrabold tracking-tight leading-none text-dark-950 dark:text-white">
            Visualize & Offset <br />
            Your <span className="text-gradient">Carbon Footprint</span>
          </h1>
          <p className="text-dark-500 dark:text-dark-400 text-lg max-w-lg leading-relaxed">
            Carbonlytix gives you the exact calculators, analytics, gamification elements, and custom insights needed to live a balanced, eco-friendly lifestyle.
          </p>
          <div className="flex flex-col sm:flex-row gap-4 mt-2">
            <Link to="/signup" className="btn-primary text-base px-6 py-3 rounded-xl">
              Create Your Free Account <ArrowRight className="w-5 h-5" />
            </Link>
            <a href="#features" className="btn-secondary text-base px-6 py-3 rounded-xl justify-center">
              Explore Features
            </a>
          </div>
        </div>
        
        {/* Floating Mock Graphic */}
        <div className="flex-1 relative w-full flex justify-center items-center">
          <div className="w-80 h-80 lg:w-96 lg:h-96 rounded-full bg-brand-500/10 absolute filter blur-3xl animate-pulse-subtle" />
          <motion.div 
            initial={{ y: 20, opacity: 0 }}
            animate={{ y: 0, opacity: 1 }}
            transition={{ duration: 0.8 }}
            className="glass-panel border border-brand-500/30 p-6 rounded-2xl max-w-md w-full shadow-2xl relative z-10 animate-float"
          >
            <div className="flex justify-between items-center mb-6">
              <span className="font-bold font-sans text-sm text-dark-400 uppercase tracking-wider">Footprint Index</span>
              <span className="px-2.5 py-1 text-xs font-semibold rounded-full bg-brand-500/15 text-brand-500">Eco level: Champion</span>
            </div>
            <div className="flex items-baseline gap-2 mb-2">
              <span className="text-4xl font-extrabold">2.4</span>
              <span className="text-dark-400 text-sm">tons CO2e / year</span>
            </div>
            <p className="text-xs text-dark-400 mb-6">↓ 42% below the national average threshold limit</p>
            
            {/* Mock chart graphics */}
            <div className="flex flex-col gap-2">
              <div className="flex justify-between text-xs font-medium">
                <span>Transportation</span>
                <span className="text-brand-500">35%</span>
              </div>
              <div className="w-full bg-dark-800 rounded-full h-2">
                <div className="bg-brand-500 h-2 rounded-full" style={{ width: '35%' }} />
              </div>
              <div className="flex justify-between text-xs font-medium mt-2">
                <span>Food Habits</span>
                <span className="text-cyan-500">20%</span>
              </div>
              <div className="w-full bg-dark-800 rounded-full h-2">
                <div className="bg-cyan-500 h-2 rounded-full" style={{ width: '20%' }} />
              </div>
            </div>
          </motion.div>
        </div>
      </section>

      {/* Stats Counter Section */}
      <section className="bg-dark-900 border-y border-dark-800 py-12 text-white">
        <div className="max-w-7xl mx-auto px-6 grid grid-cols-2 lg:grid-cols-4 gap-8 text-center">
          {stats.map((s, idx) => (
            <div key={idx} className="flex flex-col gap-1">
              <span className="text-3xl lg:text-4xl font-bold font-sans text-brand-400">{s.value}</span>
              <span className="text-dark-400 text-sm font-medium">{s.label}</span>
            </div>
          ))}
        </div>
      </section>

      {/* Features Grid */}
      <section id="features" className="py-24 px-6 max-w-7xl mx-auto">
        <div className="text-center flex flex-col gap-4 mb-16">
          <h2 className="text-3xl lg:text-4xl font-bold text-dark-950 dark:text-white">
            Everything You Need to Drive Real Change
          </h2>
          <p className="text-dark-500 dark:text-dark-400 max-w-xl mx-auto">
            From granular logging to interactive PDF reports, Carbonlytix packs professional climate tracking tools inside a premium interface.
          </p>
        </div>

        <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-6">
          {features.map((f, idx) => {
            const Icon = f.icon;
            return (
              <div key={idx} className="glass-card p-6 rounded-2xl text-left flex flex-col gap-4">
                <div className={`p-3 rounded-xl w-fit ${f.color}`}>
                  <Icon className="w-6 h-6" />
                </div>
                <h3 className="font-bold text-lg text-dark-950 dark:text-white">{f.title}</h3>
                <p className="text-dark-500 dark:text-dark-400 text-sm leading-relaxed">{f.description}</p>
              </div>
            );
          })}
        </div>
      </section>

      {/* Sustainability FAQ section */}
      <section className="py-20 bg-dark-100/30 dark:bg-dark-900/25 border-y border-dark-200 dark:border-dark-900/50 px-6">
        <div className="max-w-4xl mx-auto">
          <div className="text-center flex flex-col gap-4 mb-12">
            <h2 className="text-3xl font-bold text-dark-950 dark:text-white">Frequently Asked Questions</h2>
            <p className="text-dark-500 dark:text-dark-400">Common questions about carbon footprints and our platform.</p>
          </div>
          <div className="flex flex-col gap-4">
            {faqs.map((faq, idx) => (
              <div key={idx} className="glass-panel p-6 rounded-xl text-left">
                <div className="flex gap-3 items-start">
                  <HelpCircle className="w-5 h-5 text-brand-500 flex-shrink-0 mt-0.5" />
                  <div>
                    <h4 className="font-semibold text-dark-950 dark:text-white mb-2">{faq.q}</h4>
                    <p className="text-dark-500 dark:text-dark-400 text-sm leading-relaxed">{faq.a}</p>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Newsletter Signup footer */}
      <section className="py-20 px-6 max-w-5xl mx-auto text-center">
        <div className="glass-panel p-8 lg:p-12 rounded-3xl flex flex-col items-center gap-6 border border-brand-500/20 relative overflow-hidden">
          <div className="w-64 h-64 rounded-full bg-brand-500/5 absolute -top-32 -left-32 filter blur-2xl" />
          <Mail className="w-10 h-10 text-brand-500" />
          <h3 className="text-2xl lg:text-3xl font-bold text-dark-950 dark:text-white">Stay Updated on Climate Action</h3>
          <p className="text-dark-500 dark:text-dark-400 max-w-md text-sm leading-relaxed">
            Subscribe to our bi-weekly newsletter containing local green habits, carbon reduction tips, and featured platform challenges.
          </p>
          
          {subscribed ? (
            <motion.div 
              initial={{ scale: 0.9, opacity: 0 }}
              animate={{ scale: 1, opacity: 1 }}
              className="flex items-center gap-2 text-brand-600 dark:text-brand-400 font-semibold text-sm"
            >
              <UserCheck className="w-5 h-5" />
              <span>Thank you for subscribing! Check your inbox soon.</span>
            </motion.div>
          ) : (
            <form onSubmit={handleSubscribe} className="flex flex-col sm:flex-row gap-3 w-full max-w-md">
              <input
                type="email"
                required
                placeholder="Enter your email address"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                className="form-input flex-1 dark:bg-dark-900 border-dark-300 dark:border-dark-800"
              />
              <button type="submit" className="btn-primary py-3 px-6 rounded-xl text-sm font-semibold">
                Subscribe
              </button>
            </form>
          )}
        </div>
      </section>

      {/* Footer copyright */}
      <footer className="border-t border-dark-200 dark:border-dark-900/50 py-8 text-center text-xs text-dark-500 dark:text-dark-400">
        <p>© {new Date().getFullYear()} Carbonlytix Platform. All rights reserved.</p>
        <div className="flex justify-center gap-6 mt-4">
          <a href="#" className="hover:text-brand-500 transition-colors">Privacy Policy</a>
          <a href="#" className="hover:text-brand-500 transition-colors">Terms of Service</a>
          <a href="#" className="hover:text-brand-500 transition-colors">Contact Support</a>
        </div>
      </footer>
    </div>
  );
};

export default LandingPage;
